Added Pseudocode for Stock Span
Just-A-Visitor/Algorithmic-Pseudocode pull request #54
Opened 2019-10-24 04:45 UTC by codeboy5

2019-10-24 06:22 UTC, ghost requested changes

2019-10-24 06:22 UTC, ghost commented on Pseudocode/Stack/Stock Span/SourceCode.tex
> +                \Statex
Remove this `\Statex` as the `while` loop looks separated from the body of the `for` loop.

2019-10-24 06:22 UTC, ghost commented on Pseudocode/Stack/Stock Span/SourceCode.tex
> +            \For{$ i = 1 : len$}
Define a macro (in the preamble) by `\newcommand{\To}{\textbf{ to }}`.

Now use this macro instead of `:`. Remember to use it inside the math-mode, (that is why there is a space before and after). 

Syntax --- `\For{$ i = 1 \To len$}`

2019-10-24 06:22 UTC, ghost commented on Pseudocode/Stack/Stock Span/SourceCode.tex
> +        \Function {$Calculate\_Stock\_Span$}{$prices,len$}
Don't pass `len` as an argument. Also, the name of the array is `price` and not `prices`

2019-10-24 06:22 UTC, ghost commented on Pseudocode/Stack/Stock Span/SourceCode.tex
> +            \Statex
After the new line, extract the length manually by `\State $len \gets price.length$`

2019-10-24 06:22 UTC, ghost commented on Pseudocode/Stack/Stock Span/SourceCode.tex
> +                    \State $span[i] \gets (i+1)$
This is a serious bug. If you use 1 based indexing, it should be `i` instead of `i + 1`. Think why.

Also, remove the brackets and just write `i`

2019-10-24 06:22 UTC, ghost commented on Pseudocode/Stack/Stock Span/SourceCode.tex
> +\newcommand{\Break}{\textbf{Break}}
`Break` is used unnecessarily in this program. Remove this macro.

2019-10-24 06:22 UTC, ghost commented on Pseudocode/Stack/Stock Span/SourceCode.tex
> +\newcommand{\IsNotEmpty}{\textbf{ is not empty,}}
Don't make `is` as bold. Redefine your macro by `\newcommand{\IsNotEmpty}{is \textbf{not empty, }}`.

This is a tricky macro. Don't use it inside math-mode as it creates spacing issues.

2019-10-24 06:22 UTC, Just-A-Visitor commented on Pseudocode/Stack/Stock Span/SourceCode.tex
> +                    \EndIf
This line is unnecessary (and it wasn't even there in the code that you shared? Why did you over complicate it?

Delete this segment

2019-10-24 06:22 UTC, Just-A-Visitor commented on Pseudocode/Stack/Stock Span/SourceCode.tex
> +                    \If{$price$[$stack.top$] $<=$ $price$[$i$]}
To write `<=` in LaTeX, use the command `\leq`.

Moreover, you don't need to close the math mode-after every term.

The correct way `$price[stack.top] \leq price[i]$`

2019-10-24 06:22 UTC, Just-A-Visitor commented on Pseudocode/Stack/Stock Span/SourceCode.tex
> +                \While{$stack \IsNotEmpty$}
Replace this while loop by 

`\While{$stack$ \IsNotEmpty and $price[stack.top] \leq price[i]$}`
`\State $stack.pop$`
`\EndWhile`

Of course, take care of the indentation.

You'll see that that the `,` of `\IsNotEmpty` touches the `and`. 

To overcome this, give a manual space by writing `\`

so, it becomes `\While{$stack$ \IsNotEmpty \ and $price[stack.top] \leq price[i]$}`

Now, as you can see, there are a lot of boldface syntax together, and you naturally would want to make `and` bold too. However, that becomes too close to `empty`.

We'll do this by defining a new color for `and`.

First, include this at the bottom of your package declaration

`\usepackage{xcolor}`

Now, define a new macro by `\newcommand{\And}{\textcolor{violet}{and}}`

Finally, replace this `and` by `\And`. Take care of spaces by adding `\` if needed.

2019-10-24 06:22 UTC, ghost commented on Pseudocode/Stack/Stock Span/SourceCode.tex
> +
Give a blank line here using `\Statex`

2019-10-24 06:22 UTC, Just-A-Visitor commented on Pseudocode/Stack/Stock Span/SourceCode.tex
> +                \If{$stack \IsNotEmpty $}
As I said above, don't use this macro in math-mode.

2019-10-24 06:23 UTC, Just-A-Visitor commented
I've suggested some changes. Please go through them and modify your file accordingly.

Note that you do **not** need to fork again. Just keep pushing to your branch and let me know when you are done.

2019-10-24 06:25 UTC, ghost requested changes

2019-10-24 06:25 UTC, Just-A-Visitor commented on Pseudocode/Stack/Stock Span/SourceCode.tex
> +\algtext*{EndWhile}
Remove this line. We want to keep the `end while` for this question.

2019-10-25 01:47 UTC, ghost requested changes

2019-10-25 01:47 UTC, Just-A-Visitor commented on Pseudocode/Stack/Stock Span/SourceCode.tex
> +\newcommand{\IsNotEmpty}{is \textbf{not empty, }}
Remove the space after `,` . It is giving one extra space (as you can see below)

2019-10-25 01:47 UTC, Just-A-Visitor commented on Pseudocode/Stack/Stock Span/SourceCode.tex
> +                    \State $span[i] \gets i+1$
Serious bug here. If you are using one based indexing, then it should be `i` and not `i+1`

2019-10-25 01:49 UTC, Just-A-Visitor commented on Pseudocode/Stack/Stock Span/SourceCode.tex
> +                    \State $span[i] \gets (i+1)$
Why did you not change it in your commit? According to me, it should be `i` instead of `i+1` . Correct me if I'm wrong

2019-10-25 01:52 UTC, Just-A-Visitor commented on Pseudocode/Stack/Stock Span/SourceCode.tex
> +                    \State $span[i] \gets i+1$
Also include a right comment here by `\State $span[I] \gets i$ \Comment{One Based Indexing}`

2019-10-25 02:53 UTC, codeboy5 commented on Pseudocode/Stack/Stock Span/SourceCode.tex
> +                    \State $span[i] \gets (i+1)$
Yes you are correct, it should be i

2019-10-25 02:58 UTC, codeboy5 commented
I have made the changes, please have a look

2019-10-25 03:08 UTC, Just-A-Visitor commented
Looks good. 

Thank you for contribution to this repository. I hope you got to learn something new out of it.

2019-10-25 03:08 UTC, Just-A-Visitor commented
Closes #46

2019-10-25 03:08 UTC, merged

2019-10-25 03:09 UTC, codeboy5 commented
Yes, it was a good experience