Added Houser Robber DP psuedocode
Just-A-Visitor/Algorithmic-Pseudocode pull request #55
Opened 2019-10-24 09:31 UTC by bicycleman15

2019-10-24 11:34 UTC, Just-A-Visitor commented
First of all, the name of the file should be `SourceCode.tex`. Wait for the review and then you can edit it

2019-10-24 11:35 UTC, Just-A-Visitor commented
You should've consulted me before writing the pseudocode. Next time, please discuss the approach and the plan for writing the pseudocode

2019-10-24 11:39 UTC, ghost requested changes

2019-10-24 11:39 UTC, Just-A-Visitor commented on Pseudocode/Dynamic Programming/House Robber/houserobber.tex
> +    \Function{$rob$}{$arr$}
Name the function `House_Robber`

2019-10-24 11:39 UTC, Just-A-Visitor commented on Pseudocode/Dynamic Programming/House Robber/houserobber.tex
> +    \Ensure Zero Based Indexing for the array
Use 1 based indexing throughout your code.

2019-10-24 11:39 UTC, Just-A-Visitor commented on Pseudocode/Dynamic Programming/House Robber/houserobber.tex
> +        \Statex
A useless new line. The code looks quite separated. Remove it.

2019-10-24 11:39 UTC, Just-A-Visitor commented on Pseudocode/Dynamic Programming/House Robber/houserobber.tex
> +        \Statex
We also don't need this line. Remove it

2019-10-24 11:39 UTC, Just-A-Visitor commented on Pseudocode/Dynamic Programming/House Robber/houserobber.tex
> +        \State \Return $dp[n-1]$
Update accordingly

2019-10-24 11:40 UTC, Just-A-Visitor commented
Please make the required changes. (I'll suggest more once you're done with this).

2019-10-24 11:42 UTC, Just-A-Visitor commented on Pseudocode/Dynamic Programming/House Robber/houserobber.tex
> +        \State $dp[0] \gets arr[0]$
Don't assume anything about the inputs. What if negative values are allowed? Handle it by updating to `max(arr[0], 0)`

2019-10-24 11:51 UTC, Just-A-Visitor commented on Pseudocode/Dynamic Programming/House Robber/houserobber.tex
> +            \State $dp[i] = max(dp[i-1], arr[i] + dp[i-2])$
For clarity, break it into parts such as 

`\State $take\_it \gets arr[i] + dp[i-2]$`
`\State $leave\_it \gets dp[i-1]$`
`\State $dp[i] \gets max(take\_it, \ leave\_it)$`

2019-10-24 11:51 UTC, Just-A-Visitor commented
Also, your code doesn't handle the case when the array is of length 1. Handle it explicitly

2019-10-28 13:00 UTC, bicycleman15 commented
I have done the required changes. Please have a look.

2019-10-28 13:56 UTC, ghost requested changes

2019-10-28 13:56 UTC, Just-A-Visitor commented on Pseudocode/Dynamic Programming/House Robber/source.tex
> +        \State $dp[2] \gets max(arr[1],arr[2])$
Change it to `\State $dp[2] \gets max(arr[1], \ arr[2], \ 0)$`.

Note: This is to handle the case when all the elements are negative.

2019-10-28 13:57 UTC, Just-A-Visitor commented
Looks good. I have just requested a minor change. Correct it and click on `Resolve Conversation` for each comment. Ping me once you are done.

2019-10-28 13:59 UTC, Just-A-Visitor commented
Also, I see that you haven't changed the file name. Rename it to `SourceCode.tex`

2019-10-28 14:50 UTC, bicycleman15 commented
Okay I have done the changes.

2019-10-28 15:03 UTC, Just-A-Visitor commented
Good work! Thank you for your contribution to this repository. I hope you got to learn something new from this experience.

2019-10-28 15:04 UTC, Just-A-Visitor commented
Closes #46

2019-10-28 15:04 UTC, merged