Added Kth Largest Element in Stream
Just-A-Visitor/Algorithmic-Pseudocode pull request #94
Opened 2020-02-16 16:42 UTC by ymoullec

This is my version of the Kth Largest Element in a Stream Algorithm.

I kept the basic **2-function structure** that was given as a template in LeetCode.

If the priority queue uses a **heap data structure**, time complexity is :
1. O(log(n!)) for the initialization of the queue, n being the number of elements in the given array. Indeed, it requires n O(log(k)) insertions, k increasing from 1 to n as elements are inserted.
2. O(log(k)) for adding a new element from the stream. Indeed, it requires 1 insertion and 1 deletion (except for the first call after init) both of which are O(log(k)).

2020-02-17 15:02 UTC, Just-A-Visitor commented
Thanks. I'm a bit occupied till 20th, so I might not get time to review the code before that. Till then, you can look around other issues if you wish.

2020-02-17 18:31 UTC, ymoullec commented
Ok good to know.
When you do review the code, if you find any problem that can be described in less amount of time than what it takes to fix it, I'll be happy to fix it for you.

2020-02-23 04:24 UTC, ghost requested changes

2020-02-23 04:24 UTC, Just-A-Visitor commented on Pseudocode/Queue/Kth Largest Element in Stream/SourceCode.tex
> +        \LeftComment $queue$ is a priority queue: its elements are kept in ascending order.
The name's misleading. Let's use `max_heap` for clarity.

2020-02-23 04:24 UTC, Just-A-Visitor commented on Pseudocode/Queue/Kth Largest Element in Stream/SourceCode.tex
> +        \LeftComment $queue$ buffers k elements from the stream.
Try not to clutter the functions. You can include clarifications at the top. Basically, the code block and the function signature should not be too far.

2020-02-23 04:24 UTC, Just-A-Visitor commented on Pseudocode/Queue/Kth Largest Element in Stream/SourceCode.tex
> +        \For{all elements in $array$}
I prefer boldface `each`, `in`

2020-02-23 04:24 UTC, Just-A-Visitor commented on Pseudocode/Queue/Kth Largest Element in Stream/SourceCode.tex
> +    \Statex
We don't really need 2 blank lines

2020-02-23 04:24 UTC, Just-A-Visitor commented on Pseudocode/Queue/Kth Largest Element in Stream/SourceCode.tex
> +
I've added some more clarifications at the bottom.

2020-02-23 04:27 UTC, Just-A-Visitor commented
I've reviewed the code. You don't actually need to change anything. Just go through the reviews and mark them resolved once you are convinced. Then, you can just overwrite your code with this [link](https://gist.github.com/Just-A-Visitor/c51db7fa0edb352d3bb100051bf07754)

Finally, move the file to the `Heaps` folder.

2020-02-23 16:03 UTC, ymoullec commented
I think everything has been taken care of.
I've made the changes and updated my pull request.

2020-02-24 04:40 UTC, Just-A-Visitor commented
Good Work. Merged!

2020-02-24 04:40 UTC, merged