Feat(DP): Add shortest subarray sorting which sort the entire array
Just-A-Visitor/Algorithmic-Pseudocode pull request #96
Opened 2020-03-05 15:42 UTC by ayshiff

This PR solve #79

2020-03-06 12:13 UTC, Just-A-Visitor commented
First of all, amazing work with the PR. However, it does contain some typos (and bugs). I've reviewed them, please go through them once.

2020-03-06 12:21 UTC, ghost requested changes

2020-03-06 12:21 UTC, Just-A-Visitor commented on Pseudocode/Dynamic Programming/Shortest subarray sorting which sorts entire array/SourceCode.tex
> +        \LeftComment{$min\_right[i]$ denotes the maximum element to the right of i}
I think we should explicitly state that it denotes **the maximum element to the right of `i`, including i-th element**

2020-03-06 12:21 UTC, Just-A-Visitor commented on Pseudocode/Dynamic Programming/Shortest subarray sorting which sorts entire array/SourceCode.tex
> +        \LeftComment{$min\_left[i]$ denotes the maximum element to the left of i}
Typo. Maximum should be minimum.

2020-03-06 12:21 UTC, Just-A-Visitor commented on Pseudocode/Dynamic Programming/Shortest subarray sorting which sorts entire array/SourceCode.tex
> +        \State $min\_right[n - 1] \gets arr[n - 1]$
It looks like you've been confused by the notation. Remember, we are assuming one based indexing (See at the top of the function declaration). So, it should actually start from `n`

2020-03-06 12:21 UTC, Just-A-Visitor commented on Pseudocode/Dynamic Programming/Shortest subarray sorting which sorts entire array/SourceCode.tex
> +        \For{$ i = n$ - 1 : -1}
Indexing error. 
Moreover, I prefer to use boldface **down to** instead of `:`.
The ending indexing should be 1 and not -1.

2020-03-06 12:21 UTC, Just-A-Visitor commented on Pseudocode/Dynamic Programming/Shortest subarray sorting which sorts entire array/SourceCode.tex
> +        \State $max\_left[0] \gets arr[0]$
Indexing error.

2020-03-06 12:21 UTC, Just-A-Visitor commented on Pseudocode/Dynamic Programming/Shortest subarray sorting which sorts entire array/SourceCode.tex
> +        \For{$ i = 1 : n$}
Use **to**.

2020-03-06 12:21 UTC, Just-A-Visitor commented on Pseudocode/Dynamic Programming/Shortest subarray sorting which sorts entire array/SourceCode.tex
> +            \State $max\_left[i] \gets min(arr[i], max\_left[i - 1])$
Serious bug. Should be max

2020-03-06 12:21 UTC, Just-A-Visitor commented on Pseudocode/Dynamic Programming/Shortest subarray sorting which sorts entire array/SourceCode.tex
> +        \For{$ i = 0 : n$}
Indexing error

2020-03-06 12:21 UTC, Just-A-Visitor commented on Pseudocode/Dynamic Programming/Shortest subarray sorting which sorts entire array/SourceCode.tex
> +        \If{$left\_index = -1$ \textbf{or} $right\_index = -1$}
Use boldface **is** in place of `=`.

2020-03-06 12:21 UTC, Just-A-Visitor commented on Pseudocode/Dynamic Programming/Shortest subarray sorting which sorts entire array/SourceCode.tex
> +            \State \Return{$right\_index - left\_index$ + 1 }
Just add a bracket `(.. + 1)`

2020-03-06 17:06 UTC, ayshiff commented
Thanks for your review @Just-A-Visitor 👍
Issues should be fixed !

2020-03-07 07:59 UTC, ghost requested changes

2020-03-07 07:59 UTC, Just-A-Visitor commented on Pseudocode/Dynamic Programming/Shortest subarray sorting which sorts entire array/SourceCode.tex
> +        \LeftComment{$min\_right[i]$ denotes the maximum element to the right of i, including i-th element}
Typo. Should be `minimum`

2020-03-07 07:59 UTC, Just-A-Visitor commented on Pseudocode/Dynamic Programming/Shortest subarray sorting which sorts entire array/SourceCode.tex
> +        \For{$ i = 1 \To n$}
Loop should start from 2.

2020-03-07 07:59 UTC, Just-A-Visitor commented on Pseudocode/Dynamic Programming/Shortest subarray sorting which sorts entire array/SourceCode.tex
> +        \For{$ i = n$ \Downto $1$}
Loop should start from n-1

2020-03-07 12:02 UTC, Just-A-Visitor commented
Good Work! Merged

2020-03-07 12:02 UTC, merged